name: Chat_Plugin
version: '1.0-SNAPSHOT'
main: snowsan0113.chat_Plugin.ChatPlugin
api-version: '1.20'

commands:
  normal_mute:
    description: 通常ミュートするコマンド
    permission: snowsan0113.chat_plugin.command.nomral_mute
  temp_mute:
    description: 期間ミュートするコマンド
    permission: snowsan0113.chat_plugin.command.temp_mute
  get_mute:
    description: ミュートを取得するコマンド
    permission: snowsan0113.chat_plugin.command.get_mute
